package com.test.maps.model;


import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Id;


import org.springframework.data.annotation.Immutable;
import org.springframework.data.domain.Persistable;


@Entity
@Immutable
@Table(name = "maps")
public class Maps implements Persistable<UUID>{

    // Should have this be generated by spring boot,
    // I do not since my postgres database was existing prior. 
    // Will work on adding and verifying at a later time.
    @Id
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

   

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss.SSS")
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date", columnDefinition = "TIMESTAMP WITHOUT TIME ZONE")
    private Date date;

    @Column(name = "url")
	private String url;
	
    @Column(name = "file_path")
    private String file_path;
	
    @Column(name = "meta")
    private String meta;







    public Maps() {
    }


    public Maps(UUID id, Date date, String url, String file_path, String meta) {
        this.id = id;
        this.date = date;
        this.url = url;
        this.file_path = file_path;
        this.meta = meta;
    }
   

    @Override
    public boolean isNew() {
        return id == null;
    }

    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getFile_path() {
        return this.file_path;
    }

    public void setFile_path(String file_path) {
        this.file_path = file_path;
    }

    public String getMeta() {
        return this.meta;
    }

    public void setMeta(String meta) {
        this.meta = meta;
    }
	
}
